Resources:
    IoTUser:
        Type: AWS::IAM::User
        Properties:
            Policies:
            - PolicyName: joystickuseriotaccess
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                - 
                    Effect: Allow
                    Action:
                    - iot:*
                    Resource: "*"
    AccessKey:
        Type: 'AWS::IAM::AccessKey'
        Properties:
            Status: Active
            UserName: !Ref IoTUser
            
Outputs: 

    AccessKey: 
        Description: A reference to the created AccessKey
        Value: !Ref AccessKey
    
    SecretKey: 
        Description: A reference to the created AccessKey
        Value: !GetAtt AccessKey.SecretAccessKey
        
    SubmitJobSH: 
        Description: Shell script to run to export variables.
        Value: !Sub |
             #!/bin/bash
             ACCESSKEYID="${AccessKey}"
             SECRETACCESSKEY="${AccessKey.SecretAccessKey}"
